### ISSUE TITLE
querying outside of mass range results in segfault

### ISSUE THREAD

**Issue by smoh** [timothydmorton/isochrones#109]
The minimum mass of MIST grid is 0.1. When you query a value lower than that, this results in segmentation fault. A more gentle exception would be desirable.
```python
from isochrones.mist import MIST_EvolutionTrack
mist_track = MIST_EvolutionTrack()
mist_track.get_eep(0.08, 9.51, 0.)
mist_track.generate(0.08, 9.51, 0.)
```

**Comment by timothydmorton** [comment]
Interesting-- I get nan's when running this.  What version of isochrones are you running?
<img width="542" alt="Screenshot 2019-12-12 17 22 39" src="https://user-images.githubusercontent.com/1895387/70762051-1eadc200-1d04-11ea-8669-21f6a43c6489.png">

**Comment by smoh** [comment]
```sh
➜ pip freeze | grep isochrones
isochrones==2.0.1
```
hmm.. I had this problem on a linux machine and could reproduce it on mac osx 10.14.6 with a new conda environment:
```
conda create -n isochrones-test python=3
conda activate isochrones-test
conda install numba
pip install isochrones
```

**Comment by smoh** [comment]
I tried with the latest master of isochrones and it returns nan without segfaulting so I guess you must have fixed it between then and now.
