### ISSUE TITLE
HST ACS/WFC bands

### ISSUE THREAD

**Issue by vedantchandra** [timothydmorton/isochrones#127]
Hello,

It seems that the HST bands are not currently implemented in the bolometric correction code, even though BC grids are available on the MIST website. Is this something you were planning on implementing in the future, or is there some way I can set it up myself to work with the stellar synthesis code in ``isochrones``?

Thank you!

**Comment by timothydmorton** [comment]
Thanks for pointing this out; not sure why that's not there!  You can update the `phot_bands` dictionary here to add HST (make sure the key in the dict is the same name as the file that would be downloaded from the MIST website, and the band names correspond to the columns in the table): https://github.com/timothydmorton/isochrones/blob/c1435dbe57b85e3b6defd69074e1582c52b43a6b/isochrones/mist/bc.py#L9
If you get it working, please submit a pull request!

**Comment by vedantchandra** [comment]
Ah I see, I added my bands to the dictionary and it's working like a charm. However, in order to have the bands show up in the generated data frame, I need to add my bands to the `default_bands` list.  Otherwise, if I pass `bands = ('ACS_WFC_F606W', 'ACS_WFC_F814W')` to ``generate``, I get an error. 

I'm guessing something is going wrong with the ``get_band`` method not being able to identify the new bands unless they're already 'initialized' by being in the default list. Do you have any directions for how I can rectify that? 

Would you like me to submit a PR just for the bands I'm interested in or for all the HST bolometric tables? It may be valuable to include all the correction tables in the package. 

Thank you!

**Comment by timothydmorton** [comment]
The universal pattern that the `bands = ` keyword arg should recognize is `photsystem_bandname`.  Yes, please feel free make a PR with all the HST bolometric tables!  If passing them via `bands=` still doesn't work for you (without changing `default_bands`), still open the PR and I'll check it out and see if I can see what's going on.

**Comment by vedantchandra** [comment]
I found the problem - I was calling the HST bands from `generate` without first passing them to the `EvolutionTrack` initializer. Therefore, bc_grid was getting initialized with only the default bands. 

I'll add all the other HST bands (a slightly tedious process by hand) and submit a PR. Thanks for your help!

**Comment by vedantchandra** [comment]
Resolved by PR #128
