### ISSUE TITLE
Installed in Fresh Environment and Nosetests Fail

### ISSUE THREAD

**Issue by jacobhhamer** [timothydmorton/isochrones#129]
Hello,

 I followed the instructions at https://isochrones.readthedocs.io/en/latest/install.html as given, and when running nosetests it fails. Additionally, when trying to fit using model.fit(), the same error repeats until the kernel breaks: "KeyError: '[(nan, -1.25, 361)] not in index'".

Attached is the output of nosetests, and a list of the packages in the environment. 

[nosetests_isochrones.txt](https://github.com/timothydmorton/isochrones/files/4793799/nosetests_isochrones.txt)
[environment_list.txt](https://github.com/timothydmorton/isochrones/files/4793800/environment_list.txt)

**Comment by timothydmorton** [comment]
Thanks for reporting-- I'm guessing there is some old pandas usage in there that might cause breakages for >1.0.  Do you mind checking for me if things work in a fresh env with pandas < 1.0?

**Comment by jacobhhamer** [comment]
Hey Tim,

With pandas 0.25.3, I get the same result from the nosetests.

**Comment by timothydmorton** [comment]
Strange!  I'll check this out myself.  You don't by any chance have any old `~/.isochrones` directory lying around, do you?  That's another thing that might mess things up.

**Comment by timothydmorton** [comment]
OK, I just made a new env, too.  nosetests for me gave two errors, one expected one, and one "flaky" one.  I reminded myself that in the CI I actually use pytest (https://github.com/timothydmorton/isochrones/blob/master/.travis.yml).  And so I also tried running pytests, and while the flaky one still does fail for me locally (the flaky one), I do not see the errors you report.  Try either deleting `~/.isochrones` or creating a new env, e.g., `export ISOCHRONES=~/.isochrones-test` and trying again.

**Comment by timothydmorton** [comment]
Ah.  I see you're running on Linux.  I see that I had dropped the linux builds from the Travis CI, but I don't recall why.  Let me try adding them back and see what I see.

**Comment by timothydmorton** [comment]
Oh, I recall why.  They were dying because the available linux nodes didn't have sufficient RAM to run the tests.

**Comment by jacobhhamer** [comment]
Sorry I didn't let you know I was running Linux earlier. I have just resolved the issue. I did remove /.isochrones, but that alone did not fix it. In a fresh Anaconda install of the latest release, which was installed in a non-parallel directory as my main install, I was able to get isochrones working.

**Comment by timothydmorton** [comment]
Excellent, thanks for letting me know.
