### ISSUE TITLE
Add dependences list

### ISSUE THREAD

**Issue by Gabriel-p** [timothydmorton/isochrones#13]
Trying to install this package I was forced to first install `numexpr` and ` cython`. Could this perhaps be added as needed dependencies so one knows and installs them in advance, to prevent the installation from halting twice?

**Comment by timothydmorton** [comment]
I'm guessing those must have come in via some of the other dependencies such as `pandas` or `astropy`....I've only tested this on systems that had the anacondas distribution already installed, so I'm not really actively aware of all the nodes in the dependency tree and how cleanly they resolve themselves...

**Comment by Gabriel-p** [comment]
Couldn't be `astropy` since I already had that package installed; my money is on `pandas`. Anyway, just a thought, close at will. Cheers.

**Comment by timothydmorton** [comment]
Thanks for the tip, though!  I've added an extra note in the readme about dependencies.
