### ISSUE TITLE
Luminosity gone?

### ISSUE THREAD

**Issue by ViralTheorem** [timothydmorton/isochrones#156]
The attribute mist.logL no longer exists and there are no other attributes for luminosity. How can you generate luminosity values for a star sample?

**Comment by timothydmorton** [comment]
You should be able to do `mist.interp_value(pars, ['logL'])` where `pars` are the grid params you are evaluating at.

see https://isochrones.readthedocs.io/en/latest/grid_interpolator.html for more.

**Comment by timothydmorton** [comment]
You could also easily add a `logL` method here: https://github.com/timothydmorton/isochrones/blob/c134d271950fe63bd5e84ede4530585eba3f48a4/isochrones/models.py#L375, following the others like it.  Looks like this was just an oversight!  Feel free to submit a pull request to add this!

**Comment by ViralTheorem** [comment]
Thank you very much - will have a look at submitting a pull request in the next few days.
