### ISSUE TITLE
Triangle plot is called corner now

### ISSUE THREAD

**Issue by DanielAndreasen** [timothydmorton/isochrones#26]
I get the following warning when using the code:

```
from isochrones.dartmouth import Dartmouth_Isochrones

WARNING:root:Deprecation Warning: 'triangle' has been renamed to 'corner'. This shim should continue to work but you should use 'import corner' in new code. https://github.com/dfm/corner.py
```

I think it should just be editing [line 27 here](https://github.com/timothydmorton/isochrones/blob/master/isochrones/starmodel.py#L27), but you might import it other places. And of course set `corner` as a new dependency.

**Comment by timothydmorton** [comment]
Yup, on my to-do list, thanks!

**Comment by DanielAndreasen** [comment]
If you are busy, and it isn't much more than that, I can make a pull request for you.

**Comment by timothydmorton** [comment]
Sure, go ahead--thanks!  Shouldn't be more than switching triangle to corner in the dependencies, imports, and in the code.
