### ISSUE TITLE
HDFStore requires PyTables

### ISSUE THREAD

**Issue by mrtommyb** [timothydmorton/isochrones#3]
I get the error:
ERROR: ImportError: HDFStore requires PyTables [pandas.io.pytables]
ERROR:astropy:ImportError: HDFStore requires PyTables

My guess is that the version of Pandas required in setup.py is not sufficiently high.

**Comment by timothydmorton** [comment]
Does it work if you upgrade pandas?

**Comment by timothydmorton** [comment]
0.14 should be plenty high enough--- probably the pandas installation doesn't require PyTables by default; I'll add pytables to the requirements here.

**Comment by timothydmorton** [comment]
see if it works for you now; just added the tables requirement.

**Comment by mrtommyb** [comment]
Thanks Tim. I will try it out later today.

**Comment by mrtommyb** [comment]
Hi Tim, I got to testing it. Works now. Thanks for putting this code out there.

**Comment by timothydmorton** [comment]
Great!
