### ISSUE TITLE
Age of the Sun

### ISSUE THREAD

**Issue by DanielAndreasen** [timothydmorton/isochrones#30]
Hi Tim,

Maybe I'm doing something embarrasing wrong, but I'm not able to get the right age of the Sun (4.567Gyr) using Dartmouth isochrones.

    import numpy as np
    from isochrones.dartmouth import Dartmouth_Isochrone
    dar = Dartmouth_Isochrone()
    mass, feh = 1.00, 0.00
    age10 = dar.agerange(mass, feh)
    age10 = np.mean(age10)
    age = 10**age10/1e9  # This is 3.490Gyr

**Comment by timothydmorton** [comment]
The agerange method returns the min and max age allowed by the models.
Outside of this range properties will be nan. There's no reason that the
mean of this range should be the age of the sun.

**Comment by DanielAndreasen** [comment]
Ahh I see. I didn't use it correctly. Thanks :)
