### ISSUE TITLE
unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by alohatri** [timothydmorton/isochrones#31]
Hello Tim, 

I just installed isochrones and I am running the example you provided in the documentation:

```
import numpy as np
from isochrones import StarModel
from isochrones.dartmouth import Dartmouth_Isochrone

#spectroscopic properties (value, uncertainty)
Teff = (5770, 80)
logg = (4.44, 0.08)
feh = (0.00, 0.10)

dar = Dartmouth_Isochrone()

model  = StarModel(dar, Teff=Teff, logg=logg, feh=feh)
```

Till here everything is working fine without any errors. However, when I execute the command:

`model.fit()`

I get the following error:

`TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'`

Can you please tell me how to fix this error.

**Comment by timothydmorton** [comment]
I'm just going through and fixing a lot of things; can you let me know if you still have this issue if you install the current github master branch?

**Comment by timothydmorton** [comment]
Closing this; please reopen if you still have this issue with v1.1.
