### ISSUE TITLE
Minage/Maxage Initialization Fails for MIST But Works for Dartmouth

### ISSUE THREAD

**Issue by kschlaufman** [timothydmorton/isochrones#47]
I can initiate a grid of Dartmouth isochrones with a minimum age with no error:

dar = Dartmouth_Isochrone(minage=(10))

But if I try the same command with MIST isochrones

mist = MIST_Isochrone(minage=(10))

I get the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-e6cb739b17ec> in <module>()
----> 1 mist = MIST_Isochrone(minage=(10))

TypeError: __init__() got an unexpected keyword argument 'minage'

**Comment by timothydmorton** [comment]
Sorry I haven't gotten around to checking this one out.  It should be an easy fix, though; feel free to do it yourself and submit a PR...

**Comment by timothydmorton** [comment]
The `minage` keyword is now deprecated; you should use `mod.set_bounds(age=(lo, hi))` on the `StarModel` object rather than setting this on the `Isochrone` object itself.  I've now included a warning to this effect.
