### ISSUE TITLE
Make StarModel compatible with stellar companions that may be detected in differing filters

### ISSUE THREAD

**Issue by atw5179** [timothydmorton/isochrones#51]
Currently, the following `star.ini` file is incompatible with StarModel because the companion stars were not all detected in the same filters.

maxAV = 0.162
RA = 287.69800
dec = 42.338718
Teff = 5465, 109
feh = 0.020, 0.150
logg = 4.449, 0.085

[twomass]
J = 11.252, 0.021
H = 10.910, 0.019
K = 10.871, 0.013

[Lick]
resolution = 0.5
separation_1 = 3.842
PA_1 = 53.056
H_1 = 4.343, 0.010000000000000231
K_1 = 4.105, 0.054999999999999716
separation_2 = 12.073
PA_2 = 256.378
H_2 = 7.488, 0.010000000000000231

Those companions that have detections in filters where others were not detected have useful color information that should be included, but currently cannot be. This would be a useful adjustment to the StarModel class.

**Comment by timothydmorton** [comment]
Just getting around to addressing outstanding issues here; this should now be fixed in the current master.

**Comment by timothydmorton** [comment]
Let me know if this works for you as needed.

**Comment by timothydmorton** [comment]
Closing this, as I now have a test using this `star.ini` file on current master.  Please re-open if you find you still have issues with this.
