### ISSUE TITLE
Fail to read Dartmouth_Isochrone

### ISSUE THREAD

**Issue by smoh** [timothydmorton/isochrones#55]
I fail to initialize Dartmouth_Isochrone:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-643606627c59> in <module>()
----> 1 dar = Dartmouth_Isochrone()

~/projects/opensource/isochrones/isochrones/dartmouth/isochrone.py in __init__(self, bands, afe, y, **kwargs)
     87                            df['feh'].values,df['MMo'].values, df['LogLLo'].values,
     88                            10**df['LogTeff'].values,df['LogG'].values,mags,tri=TRI,
---> 89                            **kwargs)
     90 
     91     def agerange(self, m, feh=0.0):

~/projects/opensource/isochrones/isochrones/isochrone.py in __init__(self, m_ini, age, feh, m_act, logL, Teff, logg, mags, tri, minage, maxage, ext_table)
    143         else:
    144             self.tri = tri
--> 145             self.mass = interpnd(self.tri,m_act)
    146 
    147         self._data = {'mass':m_act,

scipy/interpolate/interpnd.pyx in scipy.interpolate.interpnd.LinearNDInterpolator.__init__ (scipy/interpolate/interpnd.c:5484)()

scipy/interpolate/interpnd.pyx in scipy.interpolate.interpnd.NDInterpolatorBase.__init__ (scipy/interpolate/interpnd.c:2621)()

scipy/spatial/qhull.pyx in scipy.spatial.qhull.Delaunay.points (scipy/spatial/qhull.c:18892)()

AttributeError: 'Delaunay' object has no attribute '_points'
```
https://gist.github.com/smoh/ea7505cdf227feb61b49755f71f2abe2

Do you think the picked file `darthmouth.tri` is outdated or something?
(I downloaded the file for the first time as you can see)

**Comment by timothydmorton** [comment]
It is, for newer versions of scipy.  Temporary fix in #43

**Comment by smoh** [comment]
Oops, sorry I missed that issue -- I'll try that, and close this since the other one's re-opened. Thanks!

**Comment by timothydmorton** [comment]
no problem!  I'm glad you're trying things out here.  I'm just right around the corner to hopefully spending a few days cleaning a bunch of things up, so having you poking around will be useful.

**Comment by smoh** [comment]
Cool! I may have a couple more issues coming. 😉


On September 22, 2017 at 2:24:20 PM, Timothy Morton (
notifications@github.com) wrote:

no problem! I'm glad you're trying things out here. I'm just right around
the corner to hopefully spending a few days cleaning a bunch of things up,
so having you poking around will be useful.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/timothydmorton/isochrones/issues/55#issuecomment-331524509>,
or mute the thread
