### ISSUE TITLE
small things

### ISSUE THREAD

**Issue by smoh** [timothydmorton/isochrones#56]
- statements after return [here](https://github.com/timothydmorton/isochrones/blob/master/isochrones/observation.py#L336) -- must be leftover from moving it to utils.py.
- There's no mention of units of parallax/returned distance in docstring or documentation. It looks like if I input in mas, I get distance in pc.

**Comment by timothydmorton** [comment]
Thanks!  I generally need to update and improve documentation, so that's now in #59.
