### ISSUE TITLE
StarModel fails without pymultinest

### ISSUE THREAD

**Issue by kcotar** [timothydmorton/isochrones#57]
When importing the library or running the nosetests i get the following error:

> File /anaconda2/lib/python2.7/site-packages/isochrones/starmodel.py", line 16, in <module>
>     import pymultinest
> ImportError: No module named pymultinest

When going through the code I noticed that there aren't any library import checks in starmodel.py as opposed to starmodel_old.py

```
mnest_available = True
try:
    import pymultinest
except ImportError:
    logging.warning('PyMultiNest not available; only emcee fits will be possible.')
    pymultinest = None
    mnest_available = False
```

Does the new model supports computations without pymultinest being installed or should we use the old model instead?

**Comment by timothydmorton** [comment]
You can still do computations using `emcee` (though the built-in initialization may not be super-robust).  Definitely should not use the old model.  I didn't realize that was even still in the repo; I  remove it.

**Comment by timothydmorton** [comment]
That having been said, I recommend using multinest over the current automated implementation of the emcee fits.  I hope to improve this soon.

**Comment by timothydmorton** [comment]
Are you running current master?  I do see the `pymultinest` import protected in the current code, and nosetests work for me.

**Comment by kcotar** [comment]
Thank you for the answers.

I was able to compile everything and now I am using pymultinest.
