### ISSUE TITLE
Bring documentation up to date.

### ISSUE THREAD

**Issue by timothydmorton** [timothydmorton/isochrones#59]

**Comment by megbedell** [comment]
+1

One thing that would be particularly useful is clear documentation/tutorial on prior setting! I had to dig around in the code a lot to figure out how to (a) change the implicitly set maxAV and (b) see what the default priors on various parameters were.

**Comment by timothydmorton** [comment]
Sorry, I realize this was not very much information.  The branch that will become v2.0 is 'bolo'.  I have not posted instructions anywhere about that, so if you need it, I'll do that soon.
