### ISSUE TITLE
MIST B and V bands are not Tycho-2 mags

### ISSUE THREAD

**Issue by mveyette** [timothydmorton/isochrones#66]
The docstring for the MIST isochrone says that the B and V mags are Tycho-2 mags:

    :param bands: (optional)
        List of desired photometric bands.  Default list of bands is
        ``['G','B','V','J','H','K','W1','W2','W3','g','r','i','z','Kepler']``.
        Here ``B`` and ``V`` are Tycho-2 mags, `griz` are SDSS, and ``G`` is
        Gaia G-band.

However, I think it is actually using the Bessell  B and V. The get_band function in isochrones/mist/grid.py has:

        # Default to SDSS for these
        if b in ['u','g','r','i','z']:
            phot = 'SDSS'
            band = 'SDSS_{}'.format(b)
        # elif b in ['B','V']:
        #     phot = 'UBVRIplus'
        #     band = 'Tycho_{}'.format(b)
        elif b in ['U','B','V','R','I']:
            phot = 'UBVRIplus'
            band = 'Bessell_{}'.format(b)

If I want to actually use the Tycho-2 mags, I should uncomment the above and change the effective wavelengths in data/filters.txt?

Thanks!

**Comment by timothydmorton** [comment]
You're right, it looks like the documentation is out of date based on what the code is doing.

I've just pushed a fix to the master branch to allow for explicit choice of band; i.e., now you can explicitly say "Tycho_B" or "Tycho_V" and it will return correctly.

Regarding effective wavelengths, it looks like I don't have the Tycho ones in there.  Please feel free to look these up and submit a pull request.  That all being said, I hope before too long to improve the way extinction is calculated in isochrones.  Chances are the differences between Bessel and Tycho are probably small compared to the errors made by not actually integrating over stellar spectra and filter bandpasses, especially at significant extinction.  So be wary of anything with significant extinction or very broad bandpasses!

**Comment by mveyette** [comment]
Great! Thanks!
