### ISSUE TITLE
Explore tri-cubic interpolation

### ISSUE THREAD

**Issue by timothydmorton** [timothydmorton/isochrones#7]
Would be great to be able to implement tri-cubic interpolation if it could be of comparable efficiency as the current `NDLinearInterpolator` implementation.

Maybe adapting [this](https://github.com/danielguterding/pytricubic)?

**Comment by styra** [comment]
Do you know what kind of interpolation do [padova's web calculator](http://stev.oapd.inaf.it/cgi-bin/cmd) use? nd-linear

**Comment by styra** [comment]
I wonder if it is possible pickle the returned interpolating function to disk?
We do interpolation at the first call of the star model, then save the interpolation function to disk.
If possible, the slow speed would be also acceptable, as it is once for all.

http://stackoverflow.com/questions/1253528/is-there-an-easy-way-to-pickle-a-python-function-or-otherwise-serialize-its-cod

**Comment by styra** [comment]
A question for discussion.

We use delaunay to do linear interpolation here, this don't require the input data to be grids. However, if we want cubic interpolation, the input data must be grid-like, right?

So you have to also change the data format.

**Comment by timothydmorton** [comment]
That's a good point-- unfortunately the nature of the available stellar models is that it won't be possible to make the data grid-like.  So it's not clear to me that cubic interpolation will actually be worthwhile to pursue after all.  I'll go ahead and close this issue.

**Comment by styra** [comment]
It's possible to convert the available stellar models to grids.  We can just do interpolation to get the values at each parameter grid to prepare the grid-like data for later interpolation. 

However, if the first interpolation is linear, that would make later cubic interpolation non-sense.
So, we can use distance weighted interpolation or something like kriging method to convert the non-grid data to grid data. 

This might be quite slow, anyway it's once for all.
