### ISSUE TITLE
Use EEP as a prior

### ISSUE THREAD

**Issue by msotov** [timothydmorton/isochrones#77]
Hi,

I wanted to know if it's possible to add information about the evolutionary stage of a star (reflected in the EEP column) when interpolating in StarModel? This could help a lot to constrain the parameter space for age and mass determination, especially for giant stars. 

Thanks!

**Comment by timothydmorton** [comment]
Sorry for taking so long to respond here; v2 will interpolate as a function of EEP.  Hopefully won't be too much longer.  If you would like to try it out before it's release-ready, lemme know.

**Comment by timothydmorton** [comment]
@msotov I hope v2 answered this question?  Feel free to re-open if not.
