### ISSUE TITLE
AttributeError: 'MISTEvolutionTrackGrid' object has no attribute '_age_grid'

### ISSUE THREAD

**Issue by bjnorfolk** [timothydmorton/isochrones#88]
Hi,
I've just installed the isochrones package on my university's supercomputer within a conda environment. I'm running python 3.7.3 and when I attempt to test generating synthetic properties of stars from your docs page I keep getting the attribute error "AttributeError: 'MISTEvolutionTrackGrid' object has no attribute '_age_grid' "

Any advice here would be greatly appreciated,

Cheers,

![image](https://user-images.githubusercontent.com/34231154/57590994-70297f00-7572-11e9-8a31-8fa21cdd755c.png)

**Comment by timothydmorton** [comment]
try running `tracks.initialize()`.  I should mention that in the docs as something you should do when running for the first time (both with an isochrone grid and evolution track grid).  Sometimes it is done automatically, but perhaps with `.generate` it doesn't trigger the right things if they haven't been computed already.

**Comment by bjnorfolk** [comment]
works now

Thanks
