### ISSUE TITLE
memory error with tracks.initialize()

### ISSUE THREAD

**Issue by bjnorfolk** [timothydmorton/isochrones#89]
Hi again,

When I following the steps from the doc to get a test track 

![image](https://user-images.githubusercontent.com/34231154/57666531-9e2ac400-7643-11e9-86d6-e3f2ae8d661d.png)

I run into a memory error on the supercomputer. Now my home directory has a 10gb limit but my working directory has a 10tb limit. My conda environment has to be installed in my home directory but I'm running ipython in the working directory. The issue I'm having is all the tracks are being downloaded into the .isochrones folder in my home directory, is there a way when I initialise the tracks to have the package download the tracks in the current working directory? 

Cheers,

**Comment by timothydmorton** [comment]
You should define an `$ISOCHRONES` environment variable, and that will put all the tracks/grids there.  (Another thing to add to docs, thanks!)

**Comment by bjnorfolk** [comment]
thanks again
