### ISSUE TITLE
Bug in starmodel

### ISSUE THREAD

**Issue by benmontet** [timothydmorton/isochrones#9]
Would submit a pull request but we're just about to run to lunch.

starmodel:441. "thresh*100" should be "lnprob_thresh*100". Causes failure in plotting and saving to hdf5 file.

**Comment by timothydmorton** [comment]
Ha-- yeah, I just found this myself.  It's fixed on master now; will fix release soon.

**Comment by timothydmorton** [comment]
which gets me back to #6...really should get on that one...
