### ISSUE TITLE
Support for MIST Skymapper bands

### ISSUE THREAD

**Issue by jlin0504** [timothydmorton/isochrones#90]
Hi, I would like to generate some synthetic SkyMapper bands, but I could only find the following bands:

In [349]: mist = get_ichrone('mist',tracks=True)                                        
In [350]: mist.bands                                                                    
Out[350]: ['J', 'H', 'K', 'G', 'BP', 'RP', 'W1', 'W2', 'W3', 'TESS', 'Kepler']

Is it possible to access the SkyMapper uvgriz bands? 
Apologies if this has been covered already.

**Comment by timothydmorton** [comment]
Just define the grid like this:
```
mist = get_ichrone('mist', tracks=True, bands=['SkyMapper_u', 'SkyMapper_g', ...])
```
The grids have a default set of bands, but anything contained in any of the mist bolometric correction tables is fair game. (see https://github.com/timothydmorton/isochrones/blob/master/isochrones/mist/bc.py)

**Comment by jlin0504** [comment]
Thanks! It works perfectly.
