### ISSUE TITLE
problem with get_ichrone

### ISSUE THREAD

**Issue by ggonzo47** [timothydmorton/isochrones#98]
I get the following error from the quick start example (using python 3.7.3 on MacOS High Sierra with Anaconda):

from isochrones import get_ichrone
tracks = get_ichrone('mist', tracks=True)

mass, age, feh = (1.03, 9.72, -0.11)

tracks.generate(mass, age, feh, return_dict=True) 
----------------------------------------------
Exception has occurred: IndexError
index 133 is out of bounds for axis 0 with size 133

and here is the output where it crashed:
"interpolating missing values in evolution tracks (feh=-4.0)':  86%|█████████████████▎  | 115/133 [00:00<00:00, 135.32it/s]"

**Comment by timothydmorton** [comment]
Hmm, strange... try to do the following to start fresh:

* wipe your `~/.isochrones` directory
* when you first initialize `tracks`, then execute `tracks.initialize()`

See if that works (will take a few minutes).

**Comment by timothydmorton** [comment]
Is this still an issue?

**Comment by ggonzo47** [comment]
No longer an issue. Thanks.
